#!/bin/bash

# ====================================================
# HOSPITAL FRONTEND - CLEANUP SCRIPT
# Generated by QA Agent - Quality Assessment
# ====================================================
# This script removes unused files identified in the
# comprehensive quality assessment.
#
# Total space to be freed: ~2.2MB
# ====================================================

set -e  # Exit on error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "🧹 Starting Hospital Frontend Cleanup..."
echo "================================================"
echo ""

# Create backup directory
BACKUP_DIR="./cleanup-backup-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP_DIR"
echo "✅ Created backup directory: $BACKUP_DIR"
echo ""

# Function to safely remove file
remove_file() {
    local file="$1"
    local reason="$2"
    
    if [ -f "$file" ]; then
        # Create backup
        local backup_path="$BACKUP_DIR/$(dirname "$file")"
        mkdir -p "$backup_path"
        cp "$file" "$backup_path/$(basename "$file")"
        
        # Get file size
        local size=$(du -h "$file" | cut -f1)
        
        # Remove file
        rm "$file"
        echo "🗑️  Deleted: $file ($size)"
        echo "   Reason: $reason"
        echo ""
    else
        echo "⚠️  Not found: $file (may already be deleted)"
        echo ""
    fi
}

echo "📁 REMOVING UNUSED ASSETS:"
echo "================================================"

# 1. Remove Word document (1.7MB)
remove_file "src/assets/Website Final.docx" \
    "Word document in source code - should be in docs/ or removed"

# 2. Remove typo filename
remove_file "src/assets/achievemnet 1.jpeg" \
    "Typo in filename (achievemnet vs achievement), not referenced in code"

# 3. Remove old banner logo
remove_file "src/assets/banner-logo.jpg" \
    "Old version - replaced by banner-logo-new.jpeg"

# 4. Remove default React SVG
remove_file "src/assets/react.svg" \
    "Default Vite template file, not used in project"

# 5. Remove screenshot files (development artifacts)
remove_file "src/assets/Screenshot 2025-10-07 at 1.05.56 PM.jpg" \
    "Development artifact, not used in production"

remove_file "src/assets/Screenshot 2025-10-07 at 1.06.03 PM.jpg" \
    "Development artifact, not used in production"

echo "================================================"
echo "✅ Asset cleanup complete!"
echo ""

# Calculate space saved
if [ -d "$BACKUP_DIR/src/assets" ]; then
    SAVED_SPACE=$(du -sh "$BACKUP_DIR/src/assets" | cut -f1)
    echo "💾 Space saved: ~$SAVED_SPACE"
else
    echo "💾 Space saved: Unknown (files may have been already removed)"
fi

echo ""
echo "================================================"
echo "📋 CLEANUP SUMMARY"
echo "================================================"
echo "✅ Unused assets removed: 6 files"
echo "✅ Backup created at: $BACKUP_DIR"
echo ""
echo "⚠️  IMPORTANT: Review backup before committing changes!"
echo ""
echo "To restore a file if needed:"
echo "  cp $BACKUP_DIR/src/assets/[filename] src/assets/"
echo ""
echo "To commit changes:"
echo "  git add src/assets/"
echo "  git commit -m \"Remove unused assets - QA cleanup\""
echo ""
echo "To remove backup (after verifying everything works):"
echo "  rm -rf $BACKUP_DIR"
echo ""
echo "================================================"
echo "🎉 Cleanup complete! Please test the application."
echo "================================================"

